In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_columns',None)

In [3]:
df = pd.read_csv('mushrooms.csv')
df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,stalk-shape,stalk-root,stalk-surface-above-ring,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,e,e,s,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,e,c,s,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,e,c,s,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,e,e,s,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,t,e,s,s,w,w,p,w,o,e,n,a,g

In [4]:
df.columns

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')

In [5]:
for col in df.columns:
    print(df[col].unique())
    print(df[col].nunique())
    print("--"*50)

['p' 'e']
2
----------------------------------------------------------------------------------------------------
['x' 'b' 's' 'f' 'k' 'c']
6
----------------------------------------------------------------------------------------------------
['s' 'y' 'f' 'g']
4
----------------------------------------------------------------------------------------------------
['n' 'y' 'w' 'g' 'e' 'p' 'b' 'u' 'c' 'r']
10
----------------------------------------------------------------------------------------------------
['t' 'f']
2
----------------------------------------------------------------------------------------------------
['p' 'a' 'l' 'n' 'f' 'c' 'y' 's' 'm']
9
----------------------------------------------------------------------------------------------------
['f' 'a']
2
----------------------------------------------------------------------------------------------------
['c' 'w']
2
----------------------------------------------------------------------------------------------------
['n' 'b']
2
----------------------------------------------------------------------------------------------------
['k' 'n' 'g' 'p' 'w' 'h' 'u' 'e' 'b' 'r' 'y' 'o']
12
----------------------------------------------------------------------------------------------------
['e' 't']
2
----------------------------------------------------------------------------------------------------
['e' 'c' 'b' 'r' '?']
5
----------------------------------------------------------------------------------------------------
['s' 'f' 'k' 'y']
4
----------------------------------------------------------------------------------------------------
['s' 'f' 'y' 'k']
4
----------------------------------------------------------------------------------------------------
['w' 'g' 'p' 'n' 'b' 'e' 'o' 'c' 'y']
9
----------------------------------------------------------------------------------------------------
['w' 'p' 'g' 'b' 'n' 'e' 'y' 'o' 'c']
9
----------------------------------------------------------------------------------------------------
['p']
1
----------------------------------------------------------------------------------------------------
['w' 'n' 'o' 'y']
4
----------------------------------------------------------------------------------------------------
['o' 't' 'n']
3
----------------------------------------------------------------------------------------------------
['p' 'e' 'l' 'f' 'n']
5
----------------------------------------------------------------------------------------------------
['k' 'n' 'u' 'h' 'w' 'r' 'o' 'y' 'b']
9
----------------------------------------------------------------------------------------------------
['s' 'n' 'a' 'v' 'y' 'c']
6
----------------------------------------------------------------------------------------------------
['u' 'g' 'm' 'd' 'p' 'w' 'l']
7
----------------------------------------------------------------------------------------------------

In [6]:
df.isnull().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
le = LabelEncoder()

In [9]:
for column in df.columns:
    df[column] = le.fit_transform(df[column])

In [10]:
df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,stalk-shape,stalk-root,stalk-surface-above-ring,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,1,5,2,4,1,6,1,0,1,4,0,3,2,2,7,7,0,2,1,4,2,3,5
1,0,5,2,9,1,0,1,0,0,4,0,2,2,2,7,7,0,2,1,4,3,2,1
2,0,0,2,8,1,3,1,0,0,5,0,2,2,2,7,7,0,2,1,4,3,2,3
3,1,5,3,8,1,6,1,0,1,5,0,3,2,2,7,7,0,2,1,4,2,3,5
4,0,5,2,3,0,5,1,1,0,4,1,3,2,2,7,7,0,2,1,0,3,0,1

In [11]:
X = df.drop('class', axis=1)
y = df['class']

In [12]:
X

,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,stalk-shape,stalk-root,stalk-surface-above-ring,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,5,2,4,1,6,1,0,1,4,0,3,2,2,7,7,0,2,1,4,2,3,5
1,5,2,9,1,0,1,0,0,4,0,2,2,2,7,7,0,2,1,4,3,2,1
2,0,2,8,1,3,1,0,0,5,0,2,2,2,7,7,0,2,1,4,3,2,3
3,5,3,8,1,6,1,0,1,5,0,3,2,2,7,7,0,2,1,4,2,3,5
4,5,2,3,0,5,1,1,0,4,1,3,2,2,7,7,0,2,1,0,3,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,3,2,4,0,5,0,0,0,11,0,0,2,2,5,5,0,1,1,4,0,1,2
8120,5,2,4,0,5,0,0,0,11,0,0,2,2,5,5,0,0,1,4,0,4,2
8121,2,2,4,0,5,0,0,0,5,0,0,2,2,5,5,0,1,1,4,0,1,2
8122,3,3,4,0,8,1,0,1,0,1,0,2,1,7,7,0,2,1,0,7,4,2
8123,5,2,4,0,5,0,0,0,11,0,0,2,2,5,5,0,1,1,4,4,1,2

In [13]:
y

0       1
1       0
2       0
3       1
4       0
       ..
8119    0
8120    0
8121    0
8122    1
8123    0
Name: class, Length: 8124, dtype: int32

In [14]:
from sklearn.decomposition import PCA
pca1 = PCA(n_components=7)
pca_fit = pca1.fit_transform(X)

In [15]:
pca1.explained_variance_ratio_

array([0.33758733, 0.16581098, 0.12285821, 0.06796611, 0.05831173,
       0.05092539, 0.04670841])

In [16]:
sum(pca1.explained_variance_ratio_)

0.8501681635086221

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(pca_fit,y, test_size =0.2, random_state =42)

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [19]:
lr = LogisticRegression()
lr.fit(X_train, y_train)

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

dtr = DecisionTreeClassifier()
dtr.fit(X_train, y_train)

svc = SVC()
svc.fit(X_train, y_train)

rf = RandomForestClassifier()
rf.fit(X_train,y_train)

gb = GradientBoostingClassifier()
gb.fit(X_train, y_train)

GradientBoostingClassifier()

In [20]:
y_predict1 = lr.predict(X_test)
y_predict2 = knn.predict(X_test)
y_predict3 = svc.predict(X_test)
y_predict4 = dtr.predict(X_test)
y_predict5 = rf.predict(X_test)
y_predict6 = gb.predict(X_test)

In [21]:
from sklearn.metrics import accuracy_score

In [22]:
print("Acc LR", accuracy_score(y_test, y_predict1))
print("Acc KNN", accuracy_score(y_test, y_predict2))
print("Acc SVC", accuracy_score(y_test, y_predict3))
print("Acc DTR", accuracy_score(y_test, y_predict4))
print("Acc RF", accuracy_score(y_test, y_predict5))
print("Acc GB", accuracy_score(y_test, y_predict6))

Acc LR 0.8344615384615385
Acc KNN 0.9833846153846154
Acc SVC 0.952
Acc DTR 0.9766153846153847
Acc RF 0.9969230769230769
Acc GB 0.9384615384615385

In [23]:
acc_score_df = pd.DataFrame({"Models":["LR","KNN","SVC","DTR","RF","GB"],
              "Acc_score":[accuracy_score(y_test,y_predict1),accuracy_score(y_test,y_predict2),accuracy_score(y_test,y_predict3),accuracy_score(y_test,y_predict4),accuracy_score(y_test,y_predict5),accuracy_score(y_test,y_predict6)]})

In [24]:
acc_score_df

  Models  Acc_score
0     LR   0.834462
1    KNN   0.983385
2    SVC   0.952000
3    DTR   0.976615
4     RF   0.996923
5     GB   0.938462

In [28]:
RFC = RandomForestClassifier()
RFC.fit(pca_fit,y)

RandomForestClassifier()

In [29]:
RFC

RandomForestClassifier()